baseURL = "https://moduleb-com.github.io/blog/"  # GitHub Pages の URL (必ず正しい URL に！)
languageCode = "ja"  # 日本語サイトの場合
title = "My Awesome Blog"  # あなたのブログのタイトル
theme = "hugo-blog-awesome"

[params]
  since = 2024  # サイトの開始年 (フッターに表示)
  favicon = "favicon.ico"  # ファビコンのパス (static/favicon.ico に配置)
  info = "Hugo と GitHub Pages で作成したブログです。"  # 簡単な自己紹介文

  # [params.social]  # SNS アカウント (任意)
  #   github = "your-github-username"
  #   twitter = "your-twitter-username"
  #   # ... 他の SNS

[author]
  name = "Your Name"  # あなたの名前
  avatar = "images/avatar.jpg"  # アバター画像のパス (static/images/avatar.jpg に配置)

[build]
  writeStats = true

[outputs]
  home = [ "HTML", "RSS", "JSON" ]